### PR TITLE
Support extensionless file in ContentType

### PR DESCRIPTION
**Pull request by scott-xu**
An extensionless file has no Extension attribute but do have PartName attribute in ContentType xml file. Fix https://github.com/vcsjones/OpenOpcSignTool/issues/76

### CODE REVIEW

**Comment by vcsjones** [comment]
Many thanks for the pull request. I'll look at it soon, thanks for patience.

**Comment by clairernovotny** [comment]
@vcsjones looks like this may be the cause of https://github.com/dotnet/SignService/issues/294. Merging this and getting a release out would be great!

**Comment by scott-xu** [comment]
Any chance to get this fix merged? @vcsjones

**Review by vcsjones — APPROVED** [review]

**Comment by scott-xu** [comment]
Many thanks for the merge. Any chance to push a new release to nuget? @vcsjones

**Pull request merged**
